### ISSUE TITLE
Installation Error: no Libradar

### ISSUE THREAD

**Issue by dennismzia** [pakkunandy/AndrAS-Review#1]
Greetings I appreciate the work you have done and also read the paper however when installing ie after following all requirements from the Read me file I get this error `    from tools.LiteRadar.LiteRadar.literadar import export_libs
ModuleNotFoundError: No module named 'tools.LiteRadar.LiteRadar' ` from the gitub link I see that the folder is empty maybe you forgot to push it here too?

**Comment by dennismzia** [comment]
Also from the internet Libradar and Libradar ie Literadar  modules seem not to have the ' export_libs' method I am assuming it is a custom implementation.

**Comment by pakkunandy** [comment]
Hi @dennismzia . Thanks for checking my tool. The issue is the submodule of LiteRadar. I have removed the submodule and pushed the full source code instead. You can pull the repo and run again. (p/s: I'm sorry but I haven't tested it. A bit busy now but I'll try to support ASAP).

**Comment by dennismzia** [comment]
Greetings and apologies for the late reply but it now works flawless I will be adding this to my pipeline soon and thank you for taking the time to create such a marvelous essential tools
![image](https://github.com/user-attachments/assets/db1d54d9-1937-42c9-8497-9dc3365657a4)

**Comment by pakkunandy** [comment]
Great, @dennismzia. Would you mind sharing which case study or situation/purpose you use AndrAS for? I'm curious to know.

**Comment by dennismzia** [comment]
In mobile applications there do not exist tools that can Aid in HAST ie (Human Application Security Testing) many existing tools aim to find vulnerabilities which often lead to many false positives or abandoned projects. In mobile applications knowing the attack surface is the first step and most crucial step. I was looking for a tool that could aid security researchers and pentesters like myself with this. without many false positives. and your tool has assisted in this first step. Here is a link that talks about HAST but in web https://danaepp.com/why-hast-is-important-to-api-hackers. 'A man is as good as his tools'

**Comment by pakkunandy** [comment]
Interesting, the HAST is new to me. I'm happy to hear your story more in the future. Hope you can accomplish your task. If you have any comments on my tool, just let me know. I'm also working on a research project that studies the role of threat modeling and attack surfaces in penetration testing. I hope you can join as one of the participants of the experiment in the future. I'll keep you posted!
